### ISSUE TITLE
`tea postgres@13.9`, but `pkg build postgresql.org@13.9`

### ISSUE THREAD

**Issue by abitrolly** [pkgxdev/brewkit#158]
Would be nice to somehow clear a confusion about what to build.
```sh
$ ./tea postgres@13.9 --version
resolving package graph
error: not-found: pkg: postgresql.org~13.9

inventory: 11.19.0, 12.14.0, 13.1.0, 14.7.0, 15.2.0
```
```sh
$ ./tea pkg build postgres@13.9
error: Uncaught Error: Not in pantry: postgres

https://github.com/teaxyz/pantry#contributing
      throw new TeaError('not-found: pantry: package.yml', {project}, )
            ^
    at https://deno.land/x/libtea@v0.6.2/src/hooks/usePantry.ts:49:13
    at Object.project (https://deno.land/x/libtea@v0.6.2/src/hooks/usePantry.ts:50:5)
    at file:///home/gitpod/.tea/tea.xyz/brewkit/v0.43.2/libexec/available.ts:11:26
warning: not supported on current platform
```

With some time spent scanning `teaxyz` repos, wiki and searching files, now I can deduct that the right command is `pkg build postgresql.org@13.9`, but I am kinda motivated to make `tea` work. :D

**Comment by mxcl** [comment]
we have some work that can be used to fix this [going on over at libtea](https://github.com/teaxyz/lib/pull/33)

in the meantime you can `tea pkg search postgres` to get its FQD name.
