### ISSUE TITLE
successive linux builds fail to instantiate toolchain

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#303]
at least in our docker image; possibly elsewhere:
```shell
pkgx $ bk b yarnpkg.com=3.8
env +git-scm.org +pkgx.sh/brewkit^0,^1
env -git-scm.org -pkgx.sh/brewkit^0,^1
  
  computing configuration
pkg: yarnpkg.com=3.8.0
src: /work/srcs/yarnpkg.com-3.8.0
build: /work/builds/yarnpkg.com-3.8.0
home: /work/homes/yarnpkg.com-3.8.0
install: ~/.pkgx/yarnpkg.com/v3.8.0
build-install: ~/.pkgx/yarnpkg.com/v3.8.0+brewing
  
  fetch & extract
  
  stage
rsync /work/projects/yarnpkg.com /work/builds/yarnpkg.com-3.8.0/props
error: Uncaught (in promise) AlreadyExists: File exists (os error 17): symlink '/root/.pkgx/llvm.org/v*/bin/clang' -> '/work/homes/yarnpkg.com-3.8.0/toolchain/cc'
    Deno.symlinkSync(target.string, this.string)
         ^
    at Object.symlinkSync (ext:deno_fs/30_fs.js:541:3)
    at Path.ln (https://deno.land/x/libpkgx@v0.17.0/src/utils/Path.ts:377:10)
    at symlink (file:///root/.pkgx/pkgx.sh/brewkit/v1.12.0/bin/cmd/build:178:14)
    at make_toolchain (file:///root/.pkgx/pkgx.sh/brewkit/v1.12.0/bin/cmd/build:182:5)
    at file:///root/.pkgx/pkgx.sh/brewkit/v1.12.0/bin/cmd/build:84:24
    at eventLoopTick (ext:core/01_core.js:182:7)
```

currently, `rm -rf homes/yarnpkg.com=3.8.0 && bk b yarnpkg.com=3.8` works as a workaround.

**Comment by mxcl** [comment]
I think this is a “symlinking across to a docker volume” issue

**Comment by jhheider** [comment]
could well be; any good reason not to sanitize the toolchain directory?

**Comment by jhheider** [comment]
actually, it's probably just this:

```shell
$ touch a
$ deno
Deno 1.40.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> Deno.symlinkSync("a", "b")
undefined
>
$ 
ls -l
total 0
-rw-r--r--  1 jacob  staff  0 Feb  2 13:10 a
lrwxr-xr-x  1 jacob  staff  1 Feb  2 13:10 b -> a
$ deno
Deno 1.40.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> Deno.symlinkSync("a", "b")
Uncaught AlreadyExists: File exists (os error 17): symlink 'a' -> 'b'
    at Object.symlinkSync (ext:deno_fs/30_fs.js:545:3)
    at <anonymous>:1:27
>
```
