### ISSUE TITLE
error: Uncaught (in promise) Error: pantry entry invalid. please report this bug!

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#72]
I know this is the cli, but I'm posting it here because it happens a lot when running `pkg` and I've got a lot of wip packages. In this case, I can't even use `pkg search name`.

Is there a way to just warn when using `pkg`?

```
error: Uncaught (in promise) Error: pantry entry invalid. please report this bug!

    https://github.com/teaxyz/pantry/issues/new

----------------------------------------------------->> attachment begin
apache.org/apache-arrow: undefined
<<------------------------------------------------------- attachment end
        throw new TeaError('parser: pantry: package.yml', {cause, project, filename})
              ^
    at Object.yml (https://raw.githubusercontent.com/teaxyz/cli/v0.26.0/src/hooks/usePantry.ts:114:15)
    at async Object.getProvides (https://raw.githubusercontent.com/teaxyz/cli/v0.26.0/src/hooks/usePantry.ts:51:15)
    at async file:///opt/tea/tea.xyz/brewkit/v0.15.1/libexec/search.ts:19:21
Caused by: null
```

**Comment by mxcl** [comment]
No you're right, this is brewkit.

We need to swallow errors when iterating. I can fix search, do you know what else was affected?

**Comment by magnusviri** [comment]
I just got this error again.

```
pkg search fortran
error: Uncaught (in promise) Error: bad-yaml
```

It would be nice if this error reported which file it was trying to read.

**Comment by magnusviri** [comment]
Nevermind, I updated to the latest version and this error went away.
